import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { useEffect } from 'react';
import Header from "@/components/Header";
import { useState } from 'react';


import { useStore } from '@/store/useStore';

const geistSans = Geist({
 variable: "--font-geist-sans",
  subsets: ["latin"],
});

 const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
 title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [userInfo, setUserInfo] = useState<any>(null); // Use a more specific type if available
  const hydrateCart = useStore(state => state.hydrateCart);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      // Cart hydration logic
      hydrateCart();

      // Authentication logic
      const token = localStorage.getItem('accessToken');
      if (token) {
        setIsLoggedIn(true);
        // If you store user info alongside the token, parse and set it here
        // Example: const userData = localStorage.getItem('userInfo');
        // if (userData) setUserInfo(JSON.parse(userData));
      } else {
        setIsLoggedIn(false);
        setUserInfo(null);
      }
    }
  }, [hydrateCart]); // Include hydrateCart in dependencies if it's part of component scope

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
 <Header />
        {children}
      </body>
    </html>
  );
}
